# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8484b19fb6ad8869ca9fdfc12a2997359382d65a32542663bba19a465d1b7b9447334297cbb6a8a09f78ab0949101a277757a5c8138da4462d9b3486a050d59f

test:
  secret_key_base: 0124a664e920603c8221210245caa9b830e62c2b82273cc7bbcb0ac2b3617c99dbfe0012c5d66bf9ae67dc6e92c3c0be169958285c26d6e62ba01d88743a7cf4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
